### ISSUE TITLE
bundle `ffmpeg` with prebuilt version

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/ferment#18]
It doesn't seem to be picking up system ffmpeg for some reason.

Could be because mac apps are not launched with full environment variables. ffmpeg might not be in path.

**Comment by NHQ** [comment]
I installed ffmpeg with brew on this here mac, but ferment no exec

**Comment by mmckegg** [comment]
@NHQ Can you send me the output of these commands?

```bash
$ which ffmpeg
$ echo $PATH
$ cat /etc/paths
```

Do you get the error message when you try to add an audio file or on startup?

**Comment by NHQ** [comment]
```
/usr/local/bin/ffmpeg
```
```
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
```
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

**Comment by NHQ** [comment]
A: error on trying to add audio

**Comment by mmckegg** [comment]
Hmm looks like the path settings are correct. Maybe it's a problem with the codecs.

Can you try running this with the file you were trying to add in place of `YOUR_FILE_PATH`:

```bash
$ ffmpeg -i YOUR_FILE_PATH -codec:a libvorbis -qscale:a 8 output.ogg
```

See if it throws an error.

You can also right click the "Add Audio" window and click inspect. It should display the actual error in the console.

**Comment by NHQ** [comment]
`Unknown encoder 'libvorbis'`

**Comment by mmckegg** [comment]
Ah, you need to compile ffmpeg with the correct flags to support libvorbis. 

I'm about to bundle a prebuilt ffmpeg with ferment that will have all the right codecs already. Also going to switch to opus because it's much better (streams better and better compression ratio)

**Comment by mmckegg** [comment]
Now bundled with macOS version and linux x64. Closing!
