### ISSUE TITLE
Error: could not connect to sbot

### ISSUE THREAD

**Issue by ahdinosaur** [mmckegg/ferment#21]
hey, here's a bug using the latest master (6099d8ac288afc06ae41e0d3ad1ae4cee2267d3e), with Patchwork also running in the background. :beetle: 

```
Error: could not connect to sbot
    at /home/dinosaur/repos/mmckegg/ferment/node_modules/ssb-client/index.js:87:23
    at /home/dinosaur/repos/mmckegg/ferment/node_modules/multiserver/compose.js:55:24
    at Socket.<anonymous> (/home/dinosaur/repos/mmckegg/ferment/node_modules/multiserver/plugins/net.js:31:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  Error: connect ECONNREFUSED 127.0.0.1:43761
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

using Debian Jessie and `node@6`.

**Comment by ahdinosaur** [comment]
works if i revert to 7c34572217302db5960909e631f491394167b146, so probs due to 3978057b918fe8625196623823baad0455969471.

**Comment by mmckegg** [comment]
Strange, I'm not seeing that error myself. Could be a platform specific thing.

The latest scuttlebot changed the way addresses work.

Any ideas @dominictarr?

**Comment by ahdinosaur** [comment]
works on latest [`4.0.0`](https://github.com/mmckegg/ferment/releases/tag/v0.4.0) if i enable `--use-global-ssb` while running Patchwork as the global scuttlebot. :taco: i'm happy with the workaround (get to use my Patchwork identity!), although this still seems be a bug, just not sure what's up.

**Comment by ahdinosaur** [comment]
i notice that [this line](https://github.com/mmckegg/ferment/blob/dafccdeba8bfe38209b3346f681391acbb9f4412/index.js#L205) logs

> Address: net:192.168.1.17:43761~shs:eKXPFA4wdEuqYWcqrjF33rIl76JgelaEtdUPPhXxOyk=;onion:localhost:~shs:eKXPFA4wdEuqYWcqrjF33rIl76JgelaEtdUPPhXxOyk=

where `192.168.1.17` is my current IP on my local wifi network and `eKXPFA4wdEuqYWcqrjF33rIl76JgelaEtdUPPhXxOyk=` is my public key (without the hash algorithm at the end). i find it maybe slightly weird that the `net` address is not `localhost`, but no idea.

**Comment by ahdinosaur** [comment]
more info from `netstat -lntup | grep 43761`

```
tcp        0      0 192.168.1.17:43761      0.0.0.0:*               LISTEN      9436/electron index
udp        0      0 0.0.0.0:43761           0.0.0.0:*                           9436/electron index
```

**Comment by mmckegg** [comment]
Have you tried nuking your node_modules and re-installing? A few people have been reporting strange issues with sbot since upgrading if that isn't done.

**Comment by ahdinosaur** [comment]
hah it works! :balloon:

**Comment by mmckegg** [comment]
There must be some sketchy dep in the tree somewhere that hasn't had its version bumped. Classic!
