### ISSUE TITLE
use sbot friend graph to decide if something should show on discovery page

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/ferment#26]
This means that if everyone you know unfollows someone, they disappear out of your view.

**Comment by mmckegg** [comment]
For now are using "pub friends". Only people who are followed by a pub that you accepted an invite on show up on the discovery page.

**Comment by mmckegg** [comment]
This seems to be working well enough for now, closing!

**Comment by PrasannaVenkadesh** [comment]
> Only people who are followed by a pub that you accepted an invite on show up on the discovery page.

We cannot discover peer on LAN or WLAN to follow? I am not able to see local peers on discovery page, but both peers logs that each of them are connected with each other through sbot with connect logs from ssb.

**Comment by mmckegg** [comment]
Yeah, I thought about this case, but wanted to wait until someone complained 😆 

I'll create an issue for it. Would be really nice to see local peers on the discovery page! They should show up under "who to follow" though, but it would be nice to prioritize them.
