### ISSUE TITLE
OS X Download version doesn't start

### ISSUE THREAD

**Issue by beingalink** [mmckegg/ferment#32]
As the title says. No error message, the icon bounces a few times in the dock and then exits silently.

OS X 10.11.6

**Comment by mmckegg** [comment]
Can you try starting it from the terminal and send me the output? It should display the error message if started this way.

```bash
$ /Applications/Ferment.app/Contents/MacOS/Ferment
```

**Comment by beingalink** [comment]
This results in:
'''
Log level: notice
Address: net:192.168.192.36:43761~shs:70Q1++IcNPOePWuPjmeB+Ujqcs0yqiwpzx24LQU8Xx0=
{ Error: bind EADDRINUSE 0.0.0.0:43761
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 43761 }
'''

**Comment by mmckegg** [comment]
It looks like somehow Ferment is already running. Or something else that uses port 43761.

You can run this to find out:

```bash
$ lsof -i :43761
```

Probably restarting will fix, but if not, it would be really interesting to figure out what is causing this.

**Comment by beingalink** [comment]
You were right, rebooting my laptop fixed the issue. I couldn't find out what the culprit was though since `lsof -i :43761`didn't output anything.
