### ISSUE TITLE
need a way of tagging feeds as 'ferment' profile, only replicate those ones

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/ferment#4]
This means we can get on any public server and we won't replicate all of the other stuff that's out of scope of music sharing.

I think my server is now in the process of trying to check every post in the history of patchwork for seedable torrents 😭 and has exploded. Also I don't know if ferment can cope with that sized global feed yet.

**Comment by mmckegg** [comment]
@dominictarr Any ideas how to go about selectively syncing feeds in sbot? I want to only sync feeds that have been tagged as "ferment" or something clever.

Also what mechanism should be used to do the tagging?

**Comment by mmckegg** [comment]
Here's an idea!

I could make it so any _follows_ generated by `ferment` have an additional `scope: 'ferment'` attribute. Then I could override the `friends` plugin and make it ignore any follows that don't have `scope: ferment` present.

**Comment by mmckegg** [comment]
Implemented scoped follows in c263066fd16cf9726cb3216c1e0bc106429b2e50

Rational for this change (copied from Patchwork post):

> I think it should be possible to have acquaintances that you don't introduce to your other friends by default. The ferment network is a different kind of relationship, one of a single shared interest, so there is less barrier to trusting people. But if by trusting people you'd be inadvertently FULLY trusting them with all of your friends group banter, I think that would be unexpected and unwanted behaviour.

> I think adding another layer around ferment's public pub replication of non-ferment data is important to solve this problem.

> Let me try an example. I have accounts on Facebook, Soundcloud and Twitter. I treat and perceive every one of those networks differently.

> My twitter is public. Anyone in the world can find it, So I don't post things about my personal life on there. I use it as a broadcast platform for things that I think the general public would care about and also what I trust them with. I may want to follow people on twitter for their public broadcasts too, but I'm doing this because I want to hear about the latest node updates, not because I want to know what they ate for dinner.

> My facebook is "private". It's not so much that it's secret, just personal. I am putting stuff on there that was only intended for higher trust relationships like family and friends. Pictures of my cat and where I live. Holiday selfie snaps, etc. I have "only friends of my friends can friend request me" turned on. When I "friend" someone, I'm doing this usually because I've met this person in real life, and I feel like I can trust them not to be a "creep" or have many creepy acquaintances.

> My soundcloud is completely different again. It is also public, but a very specific and focused feed. There are no opinions here, just music. It does one thing, and one thing well (at least they used to... hence my inspiration for ferment). When someone follows me on soundcloud, they don't want to see my cat photos, or latest loop drop release updates. They just want awesome music in their feed :wink: - and similarly when I follow someone on soundcloud, it's because I like their beats, not because I trust them (or more importantly their other fans) in any way.

I think it is very important to be able to have focused social networks, ones that don't spew personal data all over the place.

Closing!

**Comment by dominictarr** [comment]
I like the scoped follows idea. can you point me to where you are filtering out the torrents? we should be able to make an index for that and it will then be fast

**Comment by mmckegg** [comment]
@dominictarr here's my nasty little hack, that works surprisingly well: https://github.com/mmckegg/ferment/blob/master/lib/friends-with-scope.js#L49

I also modified the way pub invites work so that they can agree on a scope. That means non-ferment users can join my ferment pub, but they'll be ignored when replicating to ferment users:
https://github.com/mmckegg/ferment/blob/master/lib/invite-with-scope.js#L161

**Comment by dominictarr** [comment]
that code is due a rewrite anyway, we should figure out a way to meet both needs

**Comment by mmckegg** [comment]
Awesome!  

@dominictarr I'm finding replication can be pretty sketchy and unreliable (now that quite a lot of users are all coming on at the same time). My pub sometimes just stops responding and I have to restart it. I saw that you had started rewriting that. How's it coming along?

**Comment by dominictarr** [comment]
how many users? currently it creates loads of `createHistoryStream` which is multiplied by the number of connections.

**Comment by mmckegg** [comment]
So far only `22`, so not really that many. Probably the number wasn't the cause.

**Comment by dominictarr** [comment]
btw, standard practice is running sbot inside a restart loop.

`while true; do sbot server; done`

so that it restarts itself... naturally it's better to have a server that keeps running but a good p2p protocol needs to deal with crashes anyway, so that it works without crashing is a good sign.

Hmm, it's difficult for me to debug the performance of your server from here.
hmm, one thing that could help though, is a resource use monitor. track stats about
number of connections, bandwidth use, cpu use, memory use. Then we could confirm there is a problem at least!

My current prority has been making onboarding work in patchbay, which has turned into improving onboarding performance. broader picture - enabling more people to use ssb, aka scaling - so i think your problem fits into this

**Comment by mmckegg** [comment]
Yep, I think so. 

A think a good solution for the mean time (and in keeping with the ssb principles) is for someone else to also start hosting a ferment pub and I'll put their invite code on the readme too! That way if one doesn't work, they can try the other one. 

I also recall somewhere in the source code something about multi-invites (more than one pub server in a single invite). Is that a thing?

I suppose any of the existing pub servers would be fine! Just they share too much info! 😆
