### ISSUE TITLE
Emojis not working well on linux (at least on my machine :) )

### ISSUE THREAD

**Issue by ralphtheninja** [mmckegg/ferment#50]
All buttons with an emoji icon on it render to a square. Not sure if this is related to my computer or if it's related to some conversion problems. I'm using debian.

![screenshot from 2016-12-05 18 57 10](https://cloud.githubusercontent.com/assets/308049/20896234/ffa616ba-bb1c-11e6-916e-a008ed553d98.png)

**Comment by mmckegg** [comment]
Hmmm. On most screenshots I've seen from linux they do appear to work. Are emojis working for you in other apps like Chrome?

Found this which might help: https://thomashunter.name/blog/enable-emoji-fonts-on-debian-ubuntu-mint-linux/ (there are better instructions in comments)

Really I need to replace all of the emojis with actual icons. Things are pretty inconsistent across platforms. But I'm too lazy 😆

**Comment by ralphtheninja** [comment]
I was doing some emoji stuff this week and couldn't find DroidFamily. Works now! Thanks :)
